name: Publish to NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

env:
  NUGET_OUTPUT: Artifacts/NuGet

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Pack
        env:
          BUILD_VERSION: ${{ github.event.inputs.version }}
        run: |
          cd dotnet/CopilotPrReviewer
          dotnet pack \
            -c Release \
            -o ${{ env.NUGET_OUTPUT }} \
            -p:Version=$BUILD_VERSION
      
      - name: Upload Packages to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.version }}
          if-no-files-found: error
          retention-days: 7
          path: dotnet/CopilotPrReviewer/${{ env.NUGET_OUTPUT }}/*.nupkg

      - name: Publish to NuGet
        run: |
          cd dotnet/CopilotPrReviewer
          dotnet nuget push \
            --skip-duplicate ${{ env.NUGET_OUTPUT }}/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json